#ifndef PX4LITE_LOG_MESSAGE_IDS_H
#define PX4LITE_LOG_MESSAGE_IDS_H

/* Append-only IDs shared by Framework, Business, Display and the RPi decoder. */
#define PX4LITE_LOGMSG_TAKEOFF_SENSOR_FAIL 32U
#define PX4LITE_LOGMSG_TAKEOFF_POWER_FAIL  33U
#define PX4LITE_LOGMSG_THROTTLE_POWER_FAIL 34U
#define PX4LITE_LOGMSG_LANDING_FAIL        35U
#define PX4LITE_LOGMSG_MOTOR_POWER_CUTOFF  36U
#define PX4LITE_LOGMSG_LANDING_THROTTLE_REJECT 37U

#endif
