/**
 * @file px4lite_config.h
 * @brief 配置 Framework 模块开关、周期、超时、队列和任务栈。
 *
 * @details
 * 本文件只保存 Framework 层配置。BSP 引脚/外设配置放在 `bsp_config.h`，
 * Business 任务配置放在 `business_template_config.h`。所有 `_MS` 后缀宏均为真实
 * 毫秒值，不能填入 RTOS tick。
 */

#ifndef PX4LITE_CONFIG_H
#define PX4LITE_CONFIG_H

#define PX4LITE_ENABLE_GNSS                1U
#define PX4LITE_ENABLE_IMU                 1U
#define PX4LITE_ENABLE_BARO                1U
#define PX4LITE_ENABLE_BATTERY             1U
#define PX4LITE_ENABLE_LORA                1U
/* 5G-A 可通过所属服务发送 AT 指令做连接管理，不承载业务数据或 Remote ID 数据流。 */
#define PX4LITE_ENABLE_5G                  0U
#define PX4LITE_ENABLE_STORAGE             1U
/* Remote ID 由 STM32 通过 UART4 向 ESP32-S3 发送 MAVLink/OpenDroneID 消息。 */
#define PX4LITE_ENABLE_REMOTE_ID           1U
#define PX4LITE_ENABLE_DISPLAY             1U
#define PX4LITE_ENABLE_CONTROL             1U
#define PX4LITE_ENABLE_ALARM               1U
#define PX4LITE_ENABLE_COMMAND             0U
#define PX4LITE_ENABLE_LOG_POOL            0U

#define PX4LITE_SENSOR_WORK_PERIOD_MS      10U
#define PX4LITE_ESTIMATOR_PERIOD_MS        20U
#define PX4LITE_HEALTH_PERIOD_MS           100U
#define PX4LITE_COMM_PERIOD_MS             10U
#define PX4LITE_CONTROL_PERIOD_MS          20U
#define PX4LITE_MOTOR_COUNT                4U
#define PX4LITE_CONTROL_ESC_MIN_PULSE_US   1000U
#define PX4LITE_CONTROL_ESC_MAX_PULSE_US   2000U
#define PX4LITE_CONTROL_ESC_ARM_TIME_MS    2500U
#define PX4LITE_CONTROL_FAILSAFE_TIMEOUT_MS 200U
#define PX4LITE_TASK_HEARTBEAT_TIMEOUT_MS  500U
#define PX4LITE_IMU_WORK_PERIOD_MS         10U
#define PX4LITE_BARO_WORK_PERIOD_MS        1000U
#define PX4LITE_BATTERY_WORK_PERIOD_MS     1000U
#define PX4LITE_STORAGE_PERIOD_MS          50U

#define PX4LITE_TIME_LOCAL_OFFSET_S        28800U
#define PX4LITE_TIME_GNSS_SYNC_INTERVAL_MS 600000U
#define PX4LITE_TIME_SYNC_DELTA_S          1U
#define PX4LITE_TIME_STALE_MS              86400000U

#define PX4LITE_PRIORITY_SENSOR            (tskIDLE_PRIORITY + 4U)
#define PX4LITE_PRIORITY_ESTIMATOR         (tskIDLE_PRIORITY + 3U)
#define PX4LITE_PRIORITY_HEALTH            (tskIDLE_PRIORITY + 2U)
#define PX4LITE_PRIORITY_COMM              (tskIDLE_PRIORITY + 2U)
#define PX4LITE_PRIORITY_CONTROL           (tskIDLE_PRIORITY + 2U)
/* Storage 会执行阻塞 SD I/O，优先级必须低于 biz_display（idle+1）。 */
#define PX4LITE_PRIORITY_STORAGE (tskIDLE_PRIORITY)

/*
 * 硬件 watchdog 刷新入口实现前保持关闭；若未实现 BSP_WatchdogRefresh() 就打开，
 * 链接错误是预期保护。
 */
#define PX4LITE_ENABLE_HARDWARE_WATCHDOG 0U

#define PX4LITE_GNSS_STARTUP_GRACE_MS    5000U
#define PX4LITE_GNSS_OFFLINE_MS          2000U
#define PX4LITE_GNSS_MAX_AGE_MS          1500U
#define PX4LITE_IMU_STARTUP_GRACE_MS     2000U
#define PX4LITE_IMU_OFFLINE_MS           500U
#define PX4LITE_IMU_MAX_AGE_MS           200U
#define PX4LITE_IMU_STABLE_VALID_MIN     3U
#define PX4LITE_IMU_CALIBRATION_SAMPLES  500U
#define PX4LITE_IMU_CALIB_ACCEL_MIN_MG   850U
#define PX4LITE_IMU_CALIB_ACCEL_MAX_MG   1150U
#define PX4LITE_IMU_CALIB_GYRO_MAX_MDPS  5000U
#define PX4LITE_IMU_ATTITUDE_MIN_QUALITY 55U
#define PX4LITE_BARO_STARTUP_GRACE_MS    5000U
#define PX4LITE_BARO_OFFLINE_MS          3000U
#define PX4LITE_BARO_MAX_AGE_MS          2500U
#define PX4LITE_BARO_PRESSURE_MIN_PA     30000.0f
#define PX4LITE_BARO_PRESSURE_MAX_PA     110000.0f
#define PX4LITE_BARO_SEA_LEVEL_PA        101325.0f
#define PX4LITE_BARO_MAX_VERTICAL_CMS    1500
#define PX4LITE_BARO_MAX_JUMP_MM         20000
#define PX4LITE_FUSION_TIME_ALIGN_MS     1500U
#define PX4LITE_BATTERY_STARTUP_GRACE_MS 5000U
#define PX4LITE_BATTERY_OFFLINE_MS       3000U
#define PX4LITE_BATTERY_MAX_AGE_MS       2500U
#define PX4LITE_DISPLAY_STARTUP_GRACE_MS 5000U
#define PX4LITE_DISPLAY_OFFLINE_MS       3000U

/*
 * GNSS 专用恢复路径已经挂到 HealthRun，但在 BSP 恢复路径完成硬件故障注入测试前
 * 保持关闭。
 */
#define PX4LITE_GNSS_RECOVERY_ENABLE    0U
#define PX4LITE_GNSS_ERROR_THRESHOLD    3U
#define PX4LITE_GNSS_RECOVERY_DELAY_MS  1000U
#define PX4LITE_GNSS_RECOVERY_MAX_RETRY 5U

/*
 * 通用注册表恢复：Health 只监督并调用轻量 recover 回调，真正 re-init 由模块所属
 * Service 执行。recover 回调必须是“请求重初始化”形式，不能在 Health 任务中执行
 * 阻塞总线 I/O。重试限速但不设总次数上限，以支持长时间拔插后的热恢复。
 */
#define PX4LITE_RECOVERY_ENABLE          1U
#define PX4LITE_RECOVERY_ERROR_THRESHOLD 5U
#define PX4LITE_RECOVERY_DELAY_MS        2000U

#define PX4LITE_IMU_FIFO_CAPACITY        32U
#define PX4LITE_ALARM_QUEUE_LENGTH       16U
#define PX4LITE_ALARM_DEBOUNCE_MS        1000U
#define PX4LITE_COMMAND_QUEUE_LENGTH     8U

#define PX4LITE_STACK_SENSOR             512U
#define PX4LITE_STACK_ESTIMATOR          512U
#define PX4LITE_STACK_HEALTH             768U
#define PX4LITE_STACK_COMM               384U
#define PX4LITE_STACK_CONTROL            384U
#define PX4LITE_STACK_STORAGE            768U
#define PX4LITE_HEAP_MIN_FREE_BYTES      8192U

#define PX4LITE_LORA_OFFLINE_MS          8000U
#define PX4LITE_LORA_STARTUP_GRACE_MS    3000U
#define PX4LITE_LORA_RECOVERY_ENABLE     1U
#define PX4LITE_NODE_ROLE_MASTER         0U
#define PX4LITE_NODE_ROLE_SLAVE          1U
#define PX4LITE_ORG_PREFIX               "DCDW"
#define PX4LITE_REMOTE_NODE_MAX          17U

/*
 * 板卡身份配置：
 * - PX4LITE_PAIR_MASTER_ID 是当前配对网络的主机编号，产品默认固定为 1。
 * - PX4LITE_BOARD_UNIT_ID 是烧录前通常唯一需要修改的编号：
 *   1 = 主机，2 = 从机 1，3 = 从机 2，依次递增。
 * LoRa node id、MAVLink system id 和 RemoteID 的 DCDW-xxx 身份全部由同一个
 * unit id 派生，避免主从过滤、远端显示和 RemoteID 身份互相漂移。
 */
#define PX4LITE_PAIR_MASTER_ID           1U
#define PX4LITE_BOARD_UNIT_ID            3U

#if (PX4LITE_PAIR_MASTER_ID == 0U)
#error "PX4LITE_PAIR_MASTER_ID must be non-zero."
#endif
#if (PX4LITE_BOARD_UNIT_ID == 0U)
#error "PX4LITE_BOARD_UNIT_ID must be non-zero."
#endif
#if (PX4LITE_BOARD_UNIT_ID >= PX4LITE_REMOTE_NODE_MAX)
#error "PX4LITE_BOARD_UNIT_ID must be smaller than PX4LITE_REMOTE_NODE_MAX."
#endif

#define PX4LITE_MASTER_NODE_ID           PX4LITE_PAIR_MASTER_ID
#define PX4LITE_UNIT_ID                  PX4LITE_BOARD_UNIT_ID
#if (PX4LITE_BOARD_UNIT_ID == PX4LITE_PAIR_MASTER_ID)
#define PX4LITE_NODE_ROLE                PX4LITE_NODE_ROLE_MASTER
#else
#define PX4LITE_NODE_ROLE                PX4LITE_NODE_ROLE_SLAVE
#endif
#define PX4LITE_NODE_ID                  PX4LITE_BOARD_UNIT_ID
#define PX4LITE_MAVLINK_SYSTEM_ID        PX4LITE_BOARD_UNIT_ID
#define PX4LITE_MAVLINK_COMPONENT_ID     191U
#define PX4LITE_LORA_UART_BAUD_BPS       9600U /**< USART3 到 E22 的本地串口波特率，单位：bit/s。 */
#define PX4LITE_LORA_AIR_RATE_BPS        9600U /**< E22 当前空中速率，单位：bit/s。 */
#define PX4LITE_LORA_USABLE_BUDGET_BPS   3840U /**< 半双工默认单端可用发送预算，约为空中速率 40%。 */
#define PX4LITE_LORA_TX_DUTY_LIMIT_PCT   40U   /**< 半双工默认本机占空预算，预留对端发送和避让空间。 */

#define PX4LITE_MAVLINK_LINK_MODE_PRODUCT 0U
#define PX4LITE_MAVLINK_LINK_MODE_GCS     1U
#define PX4LITE_MAVLINK_LINK_MODE         PX4LITE_MAVLINK_LINK_MODE_PRODUCT
#define PX4LITE_MAVLINK_ENABLE_NAMED_VALUE_EXTENSIONS 1U
#define PX4LITE_MAVLINK_STREAM_MASK_NAVIGATION  (1UL << 0)
#define PX4LITE_MAVLINK_STREAM_MASK_ATTITUDE    (1UL << 1)
#define PX4LITE_MAVLINK_STREAM_MASK_ENVIRONMENT (1UL << 2)
#define PX4LITE_MAVLINK_STREAM_MASK_POWER       (1UL << 3)
#define PX4LITE_MAVLINK_STREAM_MASK_MODULES     (1UL << 4)
#define PX4LITE_MAVLINK_STREAM_MASK_ALARM       (1UL << 5)
#define PX4LITE_MAVLINK_STREAM_MASK_LOG         (1UL << 6)
#define PX4LITE_MAVLINK_STREAM_MASK_MOTOR       (1UL << 7)
#define PX4LITE_MAVLINK_STREAM_MASK_ALL         (PX4LITE_MAVLINK_STREAM_MASK_NAVIGATION | PX4LITE_MAVLINK_STREAM_MASK_ATTITUDE | PX4LITE_MAVLINK_STREAM_MASK_ENVIRONMENT | PX4LITE_MAVLINK_STREAM_MASK_POWER | PX4LITE_MAVLINK_STREAM_MASK_MODULES | PX4LITE_MAVLINK_STREAM_MASK_ALARM | PX4LITE_MAVLINK_STREAM_MASK_LOG | PX4LITE_MAVLINK_STREAM_MASK_MOTOR)
#define PX4LITE_MAVLINK_STREAM_LEASE_MS         8000U
#define PX4LITE_MAVLINK_STREAM_RENEW_MS         3000U
#define PX4LITE_REMOTE_VIEW_TIMEOUT_MS          180000U
#define PX4LITE_MAVLINK_LORA_SUMMARY_PERIOD_MS  1000U
#define PX4LITE_REMOTE_DATA_STALE_MS            30000U
#define PX4LITE_REMOTE_HEARTBEAT_STALE_MS       20000U
#define PX4LITE_REMOTE_LOG_ENTRY_MAX            5U
#define PX4LITE_MAVLINK_COMMAND_RETRY_MS        300U
#define PX4LITE_MAVLINK_COMMAND_RETRY_MAX       5U
#define PX4LITE_MAVLINK_LOSS_MIN_EXPECTED       32U
#define PX4LITE_MAVLINK_HEARTBEAT_SLOT_MS       150U
#define PX4LITE_MAVLINK_NODE_POLL_ENABLE        1U
#define PX4LITE_MAVLINK_NODE_POLL_PERIOD_MS     1000U
/* 双方同时远端查看时，主数据目录项按该倍数降频；HEARTBEAT、COMMAND 和 ACK 不降频。 */
#define PX4LITE_MAVLINK_MUTUAL_STREAM_THROTTLE  4U

/*
 * MAVLink 遥测消息选择。CommTask 是唯一发送拥有者，消息必须逐字段编码，不能直接
 * 发送 C 结构体内存。默认周期按两块板同程序互发的半双工 LoRa 保守预算配置，
 * 后续主从时隙、E22 空口速率和功率确定后再统一调整。
 */
#define PX4LITE_MAVLINK_ENABLE_HEARTBEAT       1U
#define PX4LITE_MAVLINK_ENABLE_GPS_RAW         1U
#define PX4LITE_MAVLINK_ENABLE_GNSS_DETAIL     1U
#define PX4LITE_MAVLINK_ENABLE_ATTITUDE        1U
#define PX4LITE_MAVLINK_ENABLE_GLOBAL_POSITION 1U
#define PX4LITE_MAVLINK_ENABLE_SYS_STATUS      1U
#define PX4LITE_MAVLINK_ENABLE_MODULE_STATE    1U
#define PX4LITE_MAVLINK_ENABLE_BATTERY_STATUS  1U
#define PX4LITE_MAVLINK_ENABLE_SCALED_PRESSURE 1U
#define PX4LITE_MAVLINK_ENABLE_STATUSTEXT      1U
#define PX4LITE_MAVLINK_ENABLE_REMOTE_STATUS   1U
#define PX4LITE_MAVLINK_ENABLE_REMOTE_MOTOR    1U
#define PX4LITE_MAVLINK_ENABLE_REMOTE_ALARM    1U
#define PX4LITE_MAVLINK_ENABLE_REMOTE_LOG      1U
#define PX4LITE_MAVLINK_ENABLE_ENV_HUMIDITY    1U

#define PX4LITE_MAVLINK_HEARTBEAT_PERIOD_MS    1000U
#define PX4LITE_MAVLINK_GPS_RAW_PERIOD_MS      4000U
#define PX4LITE_MAVLINK_GNSS_DETAIL_PERIOD_MS  10000U
#define PX4LITE_MAVLINK_ATTITUDE_PERIOD_MS     2000U
#define PX4LITE_MAVLINK_POSITION_PERIOD_MS     4000U
#define PX4LITE_MAVLINK_SYS_STATUS_PERIOD_MS   8000U
#define PX4LITE_MAVLINK_MODULE_STATE_PERIOD_MS 8000U
#define PX4LITE_MAVLINK_BATTERY_PERIOD_MS      8000U
#define PX4LITE_MAVLINK_PRESSURE_PERIOD_MS     8000U
#define PX4LITE_MAVLINK_ENV_HUMIDITY_PERIOD_MS 8000U
#define PX4LITE_MAVLINK_STATUSTEXT_PERIOD_MS   15000U
#define PX4LITE_MAVLINK_REMOTE_STATUS_PERIOD_MS 8000U
#define PX4LITE_MAVLINK_REMOTE_MOTOR_PERIOD_MS  5000U
#define PX4LITE_MAVLINK_REMOTE_ALARM_PERIOD_MS  8000U
#define PX4LITE_MAVLINK_REMOTE_LOG_PERIOD_MS    8000U
#define PX4LITE_MAVLINK_REMOTE_LOG_FULL_PERIOD_MS 30000U
#define PX4LITE_MAVLINK_REMOTE_MOTOR_URGENT_FRAMES 4U
#define PX4LITE_MAVLINK_RETRY_PERIOD_MS        250U

/*
 * ESP32-S3 RemoteID 发送配置。身份字段是生产默认值，后续可由 5G/网口命令写入配置存储后统一加载。
 * 当前阶段不新增任务，仍由 comm task 以静态缓冲逐帧调度，避免扩大任务栈压力。
 */
#define PX4LITE_REMOTEID_OPERATOR_ID             "DCDW"
#define PX4LITE_REMOTEID_SELF_ID                 "DCDW RemoteID"
#define PX4LITE_REMOTEID_MAVLINK_SYSTEM_ID       42U
#define PX4LITE_REMOTEID_MAVLINK_COMPONENT_ID    191U
#define PX4LITE_REMOTEID_TARGET_SYSTEM           0U
#define PX4LITE_REMOTEID_TARGET_COMPONENT        0U
#define PX4LITE_REMOTEID_HEARTBEAT_PERIOD_MS     1000U
#define PX4LITE_REMOTEID_BASIC_ID_PERIOD_MS      1000U
#define PX4LITE_REMOTEID_LOCATION_PERIOD_MS      1000U
#define PX4LITE_REMOTEID_SYSTEM_PERIOD_MS        1000U
#define PX4LITE_REMOTEID_OPERATOR_ID_PERIOD_MS   1000U
#define PX4LITE_REMOTEID_SELF_ID_PERIOD_MS       5000U
#define PX4LITE_REMOTEID_RETRY_PERIOD_MS         100U
#define PX4LITE_REMOTEID_STARTUP_GRACE_MS        3000U
#define PX4LITE_REMOTEID_OFFLINE_MS              3000U
#define PX4LITE_REMOTEID_TX_BUSY_TIMEOUT_MS      500U

#endif
