#ifndef DISPLAY_LOG_H
#define DISPLAY_LOG_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  DISPLAY_LOGMSG_SYSTEM_START = 0,
  DISPLAY_LOGMSG_IMU_LEVEL_WAIT,
  DISPLAY_LOGMSG_IMU_LEVEL_OK,
  DISPLAY_LOGMSG_SELFCHECK_OK,
  DISPLAY_LOGMSG_SELFCHECK_PART,
  DISPLAY_LOGMSG_SELFCHECK_FAIL,
  DISPLAY_LOGMSG_GPS_OK,
  DISPLAY_LOGMSG_GPS_NOSIG,
  DISPLAY_LOGMSG_GPS_LOST,
  DISPLAY_LOGMSG_ATT_OK,
  DISPLAY_LOGMSG_ATT_LOST,
  DISPLAY_LOGMSG_ENV_OK,
  DISPLAY_LOGMSG_ENV_LOST,
  DISPLAY_LOGMSG_COMM_OK,
  DISPLAY_LOGMSG_COMM_LOST,
  DISPLAY_LOGMSG_STORAGE_OK,
  DISPLAY_LOGMSG_STORAGE_LOST,
  DISPLAY_LOGMSG_MOTOR_OK,
  DISPLAY_LOGMSG_MOTOR_DISCONNECT,
  DISPLAY_LOGMSG_MOTOR_LOWPOWER,
  DISPLAY_LOGMSG_MOTOR1_FAIL,
  DISPLAY_LOGMSG_MOTOR2_FAIL,
  DISPLAY_LOGMSG_MOTOR3_FAIL,
  DISPLAY_LOGMSG_MOTOR4_FAIL,
  DISPLAY_LOGMSG_MOTOR_ALL_FAIL,
  DISPLAY_LOGMSG_MOTOR_DEAD,
  DISPLAY_LOGMSG_MOTOR_CHARGE,
  DISPLAY_LOGMSG_MAIN_CHARGE,
  DISPLAY_LOGMSG_ALARM_ACTIVE,
  DISPLAY_LOGMSG_ALARM_NONE,
  DISPLAY_LOGMSG_COUNT
} Display_LogMsg_t;

typedef struct {
  Display_LogMsg_t msg;
  uint32_t time_hhmmss;
} Display_MessageLogEntry_t;

void Display_LogPushMessage(Display_LogMsg_t msg, uint32_t time_hhmmss);
uint32_t Display_LogGetVersion(void);
uint16_t Display_LogCopyMessages(Display_MessageLogEntry_t *entries, uint16_t max_count, Display_MessageLogEntry_t *alarm_entry, uint8_t *alarm_valid);

#ifdef __cplusplus
}
#endif

#endif
